version: "3.8"

services:
  backend:
    image: quizz-back
    build:
      context: backend
    restart: always
    environment:
      DEBUG: 1
    ports:
      - 8010:8000
    volumes:
      - ./backend/src:/app/backend

  frontend:
    image: quizz-front
    build:
      context: frontend
    restart: always
    ports:
      - 80:80
